name: astrostat25
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12

  # Utils
  - numpy=2.1.3
  - ipykernel=6.28.0
  - pyzmq=24.0.1           # downgraded to match notebook's constraints
  - pip

  - pip:
      # Utils
      - ipywidgets==8.1.1
      - kaggle==1.5.12              # latest pip version, adjusted
      - notebook==6.5.6
      - pandas==2.2.3
      - prettytable==3.10.0
      - tqdm==4.66.2
      - wget==3.2                  # pip-only, though outdated

      # Plotting
      - matplotlib==3.10.1
      - plotly==6.0.1
      - seaborn==0.13.2
      - scikit-image==0.25.2

      # Classic
      - astropy==7.0.1
      - lmfit==1.3.1
      - scipy==1.15.2
      - statsmodels==0.14.4

      # Bayesian & MCMC
      - corner==2.1.0
      - dynesty==2.1.2
      - emcee==3.1.6
      - getdist==1.4.5
      - sbi==0.22.0

      # Machine Learning
      - astroML==1.0.2
      - optuna==3.5.0    
      - scikit-learn==1.6.1
      - xgboost==2.0.3

      # Deep Learning
      - h5py==3.11.0
      - nflows==0.14
      - tensorflow==2.19.0
      - torch==2.7.0
      - pytorch-lightning==2.5.1
